name: Add Username
on:
  push:
    paths:
      - '.github/user/*.txt'
concurrency:
  group: repo-only
  cancel-in-progress: false
permissions: write-all
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  build:
    name: 'Update File'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Editor File
        run: |
          # Kakathic
          if [ "$(ls .github/user/*.txt 2>/dev/null)" ];then
          ptat=".github/user/TK"
          for vv in .github/user/*.txt; do
          id="$(cat "$vv" | cut -d '|' -f1)"
          anid="$(cat "$vv" | cut -d '|' -f3)"
          [ "$(grep -cm1 "$id|" "$vv")" == 1 ] && sed -i "/${id}|/d" $ptat
          [ "$(grep -cm1 "$anid|" "$vv")" == 1 ] && sed -i "/${anid}|/d" $ptat
          cat "$vv" >> $ptat
          done
          cat $ptat | grep '|' 2>/dev/null | sort -n > new.log
          echo -e "\nĐọc nội dung new.log\n"
          cat new.log
          mv new.log $ptat
          else
          gh run cancel $GITHUB_RUN_ID
          sleep 5
          exit 1
          fi
      - name: Delete file
        run: |
          rm -f .github/user/*.*  
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "Auto delete file" || echo "Nothing to commit"
          git push
