name: Auto Add-On
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/add-on/*'
permissions: write-all
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  build:
    name: 'Update file'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download asset from release
        run: |
          gh release download Add-on --repo Zenlua/Add-on --pattern "up.log"
      - name: Editor File
        run: |
          # Kakathic
          if [ "$(ls .github/add-on/*.txt 2>/dev/null)" ];then
          for vv in .github/add-on/*.txt; do
          id="$(cat "$vv" | cut -d 'π' -f1)"
          author="$(cat "$vv" | cut -d 'π' -f2)"
          if [ "$(grep -cm1 $id "$vv")" == 1 ];then
          sed -i "/${id}π/d" up.log
          fi
          cat "$vv" >> up.log
          done
          cat up.log | sort -n -u > new.log
          mv new.log up.log
          else
          gh run cancel $GITHUB_RUN_ID
          sleep 5
          exit 1
          fi
      - name: Upload File
        uses: softprops/action-gh-release@v1
        with:
          name: Add-on
          tag_name: Add-on
          files: up.log
      - name: Delete file
        run: |
          rm -f .github/add-on/*.* up.log  
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "Auto delete file" || echo "Nothing to commit"
          git push
