name: CI Auto Add-on
on:
  push:
    paths:
      - '.github/add-on/*'
permissions: write-all
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  build:
    name: 'Update file'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download asset from release
        run: |
          gh release download Add-on --repo Zenlua/Add-on --pattern "up.log"
      - name: Editor File
        run: |
          echo 1
          cat up.log    
      - name: Upload File
        uses: softprops/action-gh-release@v1
        with:
          name: Add-on
          tag_name: Add-on
          files: up.log
          body_path: up.log
      - name: Delete file
        run: |
          rm -f .github/add-on/*.* up.log  
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "Auto delete file" || echo "Nothing to commit"
          git push
