name: Auto Add-On
on:
  push:
    paths:
      - '.github/add-on/*'
permissions: write-all
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  build:
    name: 'Update File'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download asset from release
        run: |
          gh release download Add-on --repo Zenlua/Add-on --pattern "up.log"
      - name: Editor File
        run: |
          # Kakathic
          if [ "$(ls .github/add-on/*.txt 2>/dev/null)" ];then
          for vv in .github/add-on/*.txt; do
          id="$(cat "$vv" | cut -d '|' -f1)"
          if [ "$(grep -cm1 "$id|" "$vv")" == 1 ];then
          sed -i "/${id}|/d" up.log
          fi
          cat "$vv" | tee -a up.log
          done
          cat up.log | sort -n -u | tee new.log
          mv new.log up.log
          else
          gh run cancel $GITHUB_RUN_ID
          sleep 5
          exit 1
          fi
      - name: Upload File
        run: |
          gh release upload Add-on up.log --clobber --repo Zenlua/Add-on
      - name: Delete file
        run: |
          rm -f .github/add-on/*.* up.log  
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "Auto delete file" || echo "Nothing to commit"
          git push
