name: Auto Apk-On
on:
  push:
    paths:
      - '.github/apk-on/*'
concurrency:
  group: repo-only
  cancel-in-progress: true
permissions: write-all
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  build:
    name: 'Update File'
    environment: delay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Editor File
        run: |
          # Kakathic
          if [ "$(ls .github/apk-on/*.txt 2>/dev/null)" ];then
          ptat=".github/apk-on/Hello"
          for vv in .github/apk-on/*.txt; do
          id="$(cat "$vv" | cut -d '|' -f2)"
          if [ "$(grep -cm1 "$id|" "$vv")" == 1 ];then
          sed -i "/${id}|/d" $ptat
          fi
          cat "$vv" >> $ptat
          done
          cat $ptat | grep '|' | sort -n > new.log
          echo -e "\nĐọc nội dung new.log\n"
          cat new.log
          mv new.log $ptat
          else
          gh run cancel $GITHUB_RUN_ID
          sleep 5
          exit 1
          fi
      - name: Delete file
        run: |
          rm -f .github/apk-on/*.*  
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "Auto delete file" || echo "Nothing to commit"
          git push

          
